"use client";
import {useState} from "react";

type IconName="grid"|"plus"|"queue"|"settings"|"play"|"spark"|"film"|"clock"|"check"|"arrow";
function Icon({name,size=18}:{name:IconName,size?:number}){
  const p={width:size,height:size,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const};
  const paths:any={
    grid:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,
    plus:<><path d="M12 5v14"/><path d="M5 12h14"/></>,
    queue:<><path d="M5 7h14"/><path d="M5 12h14"/><path d="M5 17h10"/></>,
    settings:<><path d="M12 3v3"/><path d="M12 18v3"/><path d="M3 12h3"/><path d="M18 12h3"/><circle cx="12" cy="12" r="4"/></>,
    play:<><path d="m9 7 8 5-8 5V7Z"/></>,
    spark:<><path d="m12 3-1.4 5.6L5 10l5.6 1.4L12 17l1.4-5.6L19 10l-5.6-1.4L12 3Z"/><path d="m19 16-.7 2.3L16 19l2.3.7L19 22l.7-2.3L22 19l-2.3-.7L19 16Z"/></>,
    film:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M7 5v14M17 5v14M3 9h4M17 9h4M3 15h4M17 15h4"/></>,
    clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,
    check:<><path d="m5 12 4 4L19 6"/></>,
    arrow:<><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></>
  };
  return <svg {...p}>{paths[name]}</svg>
}

export default function Home(){
  const [tab,setTab]=useState("dashboard");
  const [topic,setTopic]=useState("");
  const [language,setLanguage]=useState("Hindi");
  const [duration,setDuration]=useState("10 minutes");
  const [busy,setBusy]=useState(false),[renderBusy,setRenderBusy]=useState(false);
  const [message,setMessage]=useState(""),[project,setProject]=useState<any>(null),[jobs,setJobs]=useState<any[]>([]);
  const [schedule,setSchedule]=useState(""),[aspect,setAspect]=useState("16:9");

  async function generate(){setBusy(true);setMessage("Generating your production package...");try{const r=await fetch("/api/production",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic,language,duration})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Generation failed");setProject(d);setMessage("Project ready. Review it, then render the MP4.");}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
  async function renderVideo(){if(!project?.id)return;setRenderBusy(true);setMessage("Rendering scenes, narration and MP4 locally...");try{const r=await fetch("/api/render",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId:project.id,aspect})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Video rendering failed");setProject(d.project);setMessage("Video rendered successfully.");}catch(e:any){setMessage(e.message)}finally{setRenderBusy(false)}}
  async function refreshJobs(){const r=await fetch("/api/jobs");setJobs(await r.json())}
  async function scheduleJob(){const r=await fetch("/api/jobs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"full-production",runAt:schedule||new Date().toISOString(),payload:{topic,channel:"Darkest Nyts"}})});const d=await r.json();setJobs(x=>[...x,d]);setMessage("Production job scheduled.")}

  const nav=[['dashboard','Dashboard','grid'],['create','Create video','plus'],['queue','Production queue','queue'],['settings','Settings','settings']] as const;
  return <div className="appShell">
    <aside className="sidebar">
      <div className="brand"><div className="brandMark">DN</div><div><strong>Darkest Nyts</strong><span>STUDIO</span></div></div>
      <div className="workspace"><span className="statusDot"/> Local workspace <span className="chev">⌄</span></div>
      <nav>{nav.map(([id,label,icon])=><button key={id} className={tab===id?"navItem active":"navItem"} onClick={()=>setTab(id)}><Icon name={icon}/><span>{label}</span>{id==='queue'&&jobs.length>0?<em>{jobs.length}</em>:null}</button>)}</nav>
      <div className="sidebarBottom"><div className="miniCard"><div className="miniIcon"><Icon name="spark" size={15}/></div><div><b>AI Engine</b><span>Connected</span></div><span className="online"/></div><div className="profile"><div className="avatar">SK</div><div><b>Saroj Kumar</b><span>Creator</span></div><span className="dots">•••</span></div></div>
    </aside>
    <main className="main">
      <header className="topbar"><div><div className="crumb">DARKest NYTS / <span>{tab==='dashboard'?'OVERVIEW':tab.toUpperCase()}</span></div><h1>{tab==='dashboard'?'Good evening, Saroj.':tab==='create'?'Create a new video':tab==='queue'?'Production queue':'Studio settings'}</h1></div><div className="topActions"><div className="apiStatus"><span className="statusDot"/> OpenAI connected</div><button className="iconBtn" aria-label="Settings"><Icon name="settings"/></button><button className="btn primary" onClick={()=>setTab('create')}><Icon name="plus" size={16}/> New video</button></div></header>

      {tab==='dashboard'&&<>
        <section className="hero"><div><div className="eyebrow"><Icon name="spark" size={13}/> FACELESS CONTENT ENGINE</div><h2>Turn one idea into a<br/><span>cinematic story.</span></h2><p>Generate scripts, scenes, Hindi narration and finished videos from one workspace.</p><button className="btn primary large" onClick={()=>setTab('create')}>Create your next video <Icon name="arrow" size={17}/></button></div><div className="heroVisual"><div className="moon"/><div className="mountain m1"/><div className="mountain m2"/><div className="fog f1"/><div className="fog f2"/><div className="heroBadge"><Icon name="film" size={15}/><span>LOCAL RENDER</span><b>Ready</b></div></div></section>
        <section className="statsGrid"><div className="statCard"><span>Videos generated</span><b>24</b><small className="up">↑ 18% <i>this month</i></small></div><div className="statCard"><span>In production</span><b>01</b><small><span className="liveDot"/> Local render</small></div><div className="statCard"><span>Scheduled</span><b>11</b><small>Next upload · Tonight</small></div><div className="statCard"><span>Shorts ready</span><b>37</b><small className="up">↑ 9 <i>this week</i></small></div></section>
        <section className="contentGrid"><div className="panel pipeline"><div className="panelHead"><div><span className="panelKicker">WORKFLOW</span><h3>Production pipeline</h3></div><span className="tinyPill">LOCAL</span></div><div className="steps">{[['Idea','plus'],['Script','spark'],['Visuals','film'],['Voice','spark'],['Render','play'],['Publish','arrow']].map(([x,ic],i)=><div className="step" key={x}><div className="stepIcon"><Icon name={ic as IconName} size={16}/></div><span>{x}</span>{i<5&&<div className="stepLine"/>}</div>)}</div><div className="pipelineFooter"><span><span className="statusDot"/> All systems operational</span><button className="textBtn" onClick={()=>setTab('create')}>Start production <Icon name="arrow" size={15}/></button></div></div><div className="panel recent"><div className="panelHead"><div><span className="panelKicker">LIBRARY</span><h3>Recent productions</h3></div><button className="textBtn">View all</button></div>{[['The Last Passenger','10 min','Ready'],['Peeli Kothi','5 min','Scheduled'],['Midnight Platform','60 sec','Draft']].map((x,i)=><div className="recentRow" key={x[0]}><div className={'thumb t'+i}><span>{i===0?'17':i===1?'PK':'MP'}</span></div><div><b>{x[0]}</b><small>{x[1]} · Hindi</small></div><span className={'badge '+(x[2]==='Ready'?'ready':x[2]==='Scheduled'?'scheduled':'draft')}>{x[2]}</span></div>)}</div></section>
      </>}

      {tab==='create'&&<section className="createLayout"><div className="createMain panel"><div className="wizard"><span className="wizardStep active"><b>01</b> Story</span><span className="wizardLine"/><span className="wizardStep"><b>02</b> Generate</span><span className="wizardLine"/><span className="wizardStep"><b>03</b> Render</span></div><div className="formIntro"><span className="panelKicker">NEW PRODUCTION</span><h2>What story are we telling?</h2><p>Give the AI a topic. Darkest Nyts will shape it into a cinematic production package.</p></div><div className="field bigField"><label>Story topic</label><textarea value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. Seat number 17 — the last passenger on a midnight bus"/><div className="fieldHint"><span>Tip: specific places, objects and mysteries create stronger scenes.</span><span>{topic.length}/180</span></div></div><div className="two"><div className="field"><label>Language</label><select value={language} onChange={e=>setLanguage(e.target.value)}><option>Hindi</option><option>Hinglish</option><option>English</option></select></div><div className="field"><label>Duration</label><select value={duration} onChange={e=>setDuration(e.target.value)}><option>10 seconds</option><option>30 seconds</option><option>60 seconds</option><option>5 minutes</option><option>7 minutes</option><option>10 minutes</option></select></div></div><button className="btn primary large full" disabled={busy||renderBusy||!topic.trim()} onClick={generate}><Icon name="spark" size={17}/>{busy?'Generating story...':'Generate production package'}<Icon name="arrow" size={16}/></button>{message&&<div className={'notice '+(message.startsWith('✕')?'error':'')}><span className="noticeIcon">{message.startsWith('✕')?'!':'✓'}</span>{message}</div>}
      {project&&<div className="projectResult"><div className="resultHead"><div><span className="panelKicker">PRODUCTION READY</span><h3>{project.title}</h3></div><span className="badge ready">AI PACKAGE</span></div><div className="hook"><span>HOOK</span><p>{project.hook}</p></div><div className="renderCard"><div><span className="panelKicker">FINAL VIDEO</span><h3>Render your MP4</h3><p>Generate AI scenes, Hindi narration and a finished video locally with FFmpeg.</p></div><div className="two compact"><div className="field"><label>Format</label><select value={aspect} onChange={e=>setAspect(e.target.value)} disabled={renderBusy}><option>16:9</option><option>9:16</option></select></div><div className="field"><label>Status</label><div className="statusInput"><span className={project.videoUrl?'statusDot':''}/>{project.videoUrl?'Ready to watch':'Not rendered yet'}</div></div></div><div className="renderActions"><button className="btn primary" disabled={renderBusy} onClick={renderVideo}><Icon name="play" size={16}/>{renderBusy?'Rendering...':'Generate actual MP4'}</button>{project.videoUrl&&<a className="btn dark" href={project.videoUrl} target="_blank" rel="noreferrer"><Icon name="play" size={15}/> Open generated video</a>}</div></div><div className="scriptBlock"><div className="panelHead"><div><span className="panelKicker">STORYBOARD</span><h3>Script & scenes</h3></div><span className="tinyPill">{(project.scenes||[]).length} SCENES</span></div><div className="scriptText"><b>Script</b><p>{project.script}</p></div>{(project.scenes||[]).map((s:any)=><div className="sceneRow" key={s.number}><div className="sceneNum">{String(s.number).padStart(2,'0')}</div><div><b>{s.narration}</b><small>{s.visualPrompt}</small></div><span>{s.duration}s</span></div>)}</div></div>}
      </div><aside className="createAside"><div className="asidePanel panel"><span className="panelKicker">PREVIEW</span><div className="phonePreview"><div className="previewGlow"/><div className="previewText"><small>DARKEST NYTS</small><b>{topic||'Your next horror story'}</b><span>{language} · {duration}</span></div><div className="previewPlay"><Icon name="play" size={20}/></div></div><div className="previewMeta"><span><Icon name="film" size={14}/> Cinematic</span><span><Icon name="spark" size={14}/> AI generated</span></div></div><div className="asidePanel panel"><span className="panelKicker">BRAND</span><h3>Darkest Nyts</h3><p>Void Black · Dark Teal · Blood Red · Moon White · Warm Lantern</p><div className="swatches"><i/><i/><i/><i/><i/></div></div></aside></section>}

      {tab==='queue'&&<section className="panel queuePage"><div className="panelHead"><div><span className="panelKicker">AUTOMATION</span><h2>Production queue</h2><p>Schedule and monitor content jobs.</p></div><button className="btn" onClick={refreshJobs}>Refresh</button></div><div className="field"><label>Schedule time (ISO)</label><input value={schedule} onChange={e=>setSchedule(e.target.value)} placeholder="2026-09-21T20:30:00+05:30"/></div><button className="btn primary" onClick={scheduleJob}>Schedule production</button><div className="queueList">{jobs.length?jobs.map((j:any)=><div className="queueRow" key={j.id}><div className="queueIcon"><Icon name="clock"/></div><div><b>{j.type}</b><small>{j.runAt}</small></div><span className="badge scheduled">{j.status}</span></div>):<div className="empty"><Icon name="queue" size={28}/><b>No scheduled jobs yet</b><span>Create a production job from this screen.</span></div>}</div></section>}
      {tab==='settings'&&<section className="panel settingsPage"><div className="panelHead"><div><span className="panelKicker">WORKSPACE</span><h2>Studio settings</h2><p>Configure the identity and AI stack for your channel.</p></div></div><div className="settingsGrid"><div><div className="field"><label>Channel name</label><input defaultValue="Darkest Nyts"/></div><div className="field"><label>Brand palette</label><input defaultValue="#050708 · #102A30 · #B00012 · #E8EDF0 · #C87832"/></div></div><div><div className="field"><label>AI pipeline</label><input readOnly value="GPT-5.6 Luna · GPT-Image-2 · GPT-4o Mini TTS · FFmpeg"/></div><div className="connection"><span className="statusDot"/><div><b>OpenAI API connected</b><small>Your local API key is configured and responding.</small></div></div></div></div></section>}
    </main>
  </div>
}
